apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignition-gateway
  namespace: ignition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ignition-gateway
  template:
    metadata:
      labels:
        app: ignition-gateway
    spec:
      initContainers:
      - name: init-ignition-data
        image: inductiveautomation/ignition:latest
        command: ['sh', '-c']
        args:
          - |
            if [ ! -f /persistent-data/gateway.xml_clean ]; then
              echo "First run detected - copying Ignition system files..."
              cp -r /usr/local/bin/ignition/data/* /persistent-data/
              echo "Copy completed!"
            else
              echo "System files already present, skipping copy."
            fi
        volumeMounts:
        - name: gateway-data
          mountPath: /persistent-data
      containers:
      - name: ignition-gateway
        image: inductiveautomation/ignition:latest
        ports:
        - containerPort: 8088
          name: http
        - containerPort: 8043
          name: https
        env:
        - name: GATEWAY_ADMIN_PASSWORD
          value: "password"
        - name: IGNITION_EDITION
          value: "standard"
        - name: TZ
          value: "Europe/Paris"
        volumeMounts:
        - name: gateway-data
          mountPath: /usr/local/bin/ignition/data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: gateway-data
        persistentVolumeClaim:
          claimName: ignition-storage
---
apiVersion: v1
kind: Service
metadata:
  name: ignition-gateway-service
  namespace: ignition
spec:
  selector:
    app: ignition-gateway
  ports:
  - name: http
    port: 8088
    targetPort: 8088
    nodePort: 30088
  - name: https
    port: 8043
    targetPort: 8043
    nodePort: 30043
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ignition-storage
  namespace: ignition
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path