apiVersion: v1
kind: Namespace
metadata:
  name: ignition
---
# PVC pour le Master
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ignition-master-storage
  namespace: ignition
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
# PVC pour le Backup
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ignition-backup-storage
  namespace: ignition
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
# Deployment Master Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignition-master
  namespace: ignition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ignition-master
  template:
    metadata:
      labels:
        app: ignition-master
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: ["ignition-master", "ignition-backup"]
              topologyKey: kubernetes.io/hostname
      initContainers:
      - name: init-sql-database
        image: mcr.microsoft.com/mssql-tools
        command: ['sh', '-c']
        args:
          - |
            echo "Checking SQL Server connectivity..."
            until /opt/mssql-tools18/bin/sqlcmd -S sql-server-service.database.svc.cluster.local -U sa -P 'Sanofi123!' -C -Q "SELECT 1" > /dev/null 2>&1; do
              echo "Waiting for SQL Server to be ready..."
              sleep 5
            done
            echo "SQL Server is ready!"
            
            echo "Checking if IgnitionSCADA database exists..."
            DB_EXISTS=$(/opt/mssql-tools18/bin/sqlcmd -S sql-server-service.database.svc.cluster.local -U sa -P 'Sanofi123!' -C -Q "SELECT COUNT(*) FROM sys.databases WHERE name = 'IgnitionSCADA'" -h -1 2>/dev/null | tr -d ' \n\r')
            
            if [ "$DB_EXISTS" = "1" ]; then
              echo "IgnitionSCADA database already exists"
            else
              echo "Creating IgnitionSCADA database..."
              /opt/mssql-tools18/bin/sqlcmd -S sql-server-service.database.svc.cluster.local -U sa -P 'Sanofi123!' -C -Q "CREATE DATABASE IgnitionSCADA"
              echo "IgnitionSCADA database created successfully!"
            fi
            echo "Database initialization completed"
      - name: init-master-data
        image: inductiveautomation/ignition:latest
        command: ['sh', '-c']
        args:
          - |
            if [ ! -f /persistent-data/gateway.xml_clean ]; then
              echo "First run detected - copying Ignition system files for Master..."
              cp -r /usr/local/bin/ignition/data/* /persistent-data/
              echo "Master copy completed!"
            else
              echo "Master system files already present, skipping copy."
            fi
        volumeMounts:
        - name: master-data
          mountPath: /persistent-data
      containers:
      - name: ignition-master
        image: inductiveautomation/ignition:latest
        ports:
        - containerPort: 8088
          name: http
        - containerPort: 8043
          name: https
        - containerPort: 8060
          name: redundancy
        env:
        - name: GATEWAY_ADMIN_PASSWORD
          value: "password"
        - name: IGNITION_EDITION
          value: "standard"
        - name: TZ
          value: "Europe/Paris"
        - name: GATEWAY_REDUNDANCY_ENABLED
          value: "true"
        - name: GATEWAY_REDUNDANCY_ROLE
          value: "master"
        # Configuration SQL Server (utilise master temporairement)
        - name: IGNITION_DB_URL
          value: "jdbc:sqlserver://sql-server-service.database.svc.cluster.local:1433;databaseName=master;encrypt=false;trustServerCertificate=true"
        - name: IGNITION_DB_USERNAME
          value: "sa"
        - name: IGNITION_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ignition-sql-credentials
              key: sql_password
        volumeMounts:
        - name: master-data
          mountPath: /usr/local/bin/ignition/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: master-data
        persistentVolumeClaim:
          claimName: ignition-master-storage
---
# Deployment Backup Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignition-backup
  namespace: ignition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ignition-backup
  template:
    metadata:
      labels:
        app: ignition-backup
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: ["ignition-master", "ignition-backup"]
              topologyKey: kubernetes.io/hostname
      initContainers:
      - name: init-sql-database
        image: mcr.microsoft.com/mssql-tools
        command: ['sh', '-c']
        args:
          - |
            echo "Checking SQL Server connectivity..."
            until /opt/mssql-tools18/bin/sqlcmd -S sql-server-service.database.svc.cluster.local -U sa -P 'Sanofi123!' -C -Q "SELECT 1" > /dev/null 2>&1; do
              echo "Waiting for SQL Server to be ready..."
              sleep 5
            done
            echo "SQL Server is ready!"
            
            echo "Checking if IgnitionSCADA database exists..."
            DB_EXISTS=$(/opt/mssql-tools18/bin/sqlcmd -S sql-server-service.database.svc.cluster.local -U sa -P 'Sanofi123!' -C -Q "SELECT COUNT(*) FROM sys.databases WHERE name = 'IgnitionSCADA'" -h -1 2>/dev/null | tr -d ' \n\r')
            
            if [ "$DB_EXISTS" = "1" ]; then
              echo "IgnitionSCADA database already exists"
            else
              echo "Creating IgnitionSCADA database..."
              /opt/mssql-tools18/bin/sqlcmd -S sql-server-service.database.svc.cluster.local -U sa -P 'Sanofi123!' -C -Q "CREATE DATABASE IgnitionSCADA"
              echo "IgnitionSCADA database created successfully!"
            fi
            echo "Database initialization completed"
      - name: init-backup-data
        image: inductiveautomation/ignition:latest
        command: ['sh', '-c']
        args:
          - |
            if [ ! -f /persistent-data/gateway.xml_clean ]; then
              echo "First run detected - copying Ignition system files for Backup..."
              cp -r /usr/local/bin/ignition/data/* /persistent-data/
              echo "Backup copy completed!"
            else
              echo "Backup system files already present, skipping copy."
            fi
        volumeMounts:
        - name: backup-data
          mountPath: /persistent-data
      containers:
      - name: ignition-backup
        image: inductiveautomation/ignition:latest
        ports:
        - containerPort: 8088
          name: http
        - containerPort: 8043
          name: https
        - containerPort: 8060
          name: redundancy
        env:
        - name: GATEWAY_ADMIN_PASSWORD
          value: "password"
        - name: IGNITION_EDITION
          value: "standard"
        - name: TZ
          value: "Europe/Paris"
        - name: GATEWAY_REDUNDANCY_ENABLED
          value: "true"
        - name: GATEWAY_REDUNDANCY_ROLE
          value: "backup"
        - name: GATEWAY_REDUNDANCY_MASTER_HOSTNAME
          value: "ignition-master-service.ignition.svc.cluster.local"
        # Configuration SQL Server (utilise master temporairement)
        - name: IGNITION_DB_URL
          value: "jdbc:sqlserver://sql-server-service.database.svc.cluster.local:1433;databaseName=master;encrypt=false;trustServerCertificate=true"
        - name: IGNITION_DB_USERNAME
          value: "sa"
        - name: IGNITION_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ignition-sql-credentials
              key: sql_password
        volumeMounts:
        - name: backup-data
          mountPath: /usr/local/bin/ignition/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: backup-data
        persistentVolumeClaim:
          claimName: ignition-backup-storage
---
# Service Master Gateway
apiVersion: v1
kind: Service
metadata:
  name: ignition-master-service
  namespace: ignition
spec:
  selector:
    app: ignition-master
  ports:
  - name: http
    port: 8088
    targetPort: 8088
    nodePort: 30088
  - name: https
    port: 8043
    targetPort: 8043
    nodePort: 30043
  - name: redundancy
    port: 8060
    targetPort: 8060
  type: NodePort
---
# Service Backup Gateway
apiVersion: v1
kind: Service
metadata:
  name: ignition-backup-service
  namespace: ignition
spec:
  selector:
    app: ignition-backup
  ports:
  - name: http
    port: 8088
    targetPort: 8088
    nodePort: 30089
  - name: https
    port: 8043
    targetPort: 8043
    nodePort: 30044
  - name: redundancy
    port: 8060
    targetPort: 8060
  type: NodePort